### ISSUE TITLE
Input tuples to C UDFs

### ISSUE THREAD

**Issue by ZheyuanBu** [shlee0605/peloton#15]
I was trying to add a C user-defined function called `sum_columns` at https://github.com/shlee0605/peloton/blob/udf/src/backend/bridge/dml/expr/expr_transformer.cpp#L306.
The input of the function is a tuple and the output is an integer. It adds up the value of two attributes for each tuple in a table and returns the sum.

The function works fine in postgres. However, in peloton, the expression system does not support the representation of an entire tuple. You can see they are returning null pointer if we are trying to transform the expression of entire tuple from postgres to peloton.
https://github.com/shlee0605/peloton/blob/udf/src/backend/bridge/dml/expr/expr_transformer.cpp#L359

**Comment by shlee0605** [comment]
@ZheyuanBu Since the code explicitly says that the entire tuple is not supported, let's test with a udf that uses the types that peloton currently supports.

**Comment by ZheyuanBu** [comment]
ok, let's not worry about this issue.
