### ISSUE TITLE
Adding a test cases for C UDF

### ISSUE THREAD

**Issue by shlee0605** [shlee0605/peloton#4]
Let's list all possible tests that we need to cover in this thread.

This is the list that I can think of
- check udf function from every possible place (select X(), select . from X(), select . from . where X()...)
- check different output types(int, float, char...etc)
- check the udf with output of table (multiple tuples)

**Comment by ZheyuanBu** [comment]
Also,
- check udf function in some other places, eg. HAVING, ORDER BY, GROUP BY
- check recursive functions, eg. fib(n) = fib(n - 1) + fib(n - 2)
- test udf functions with different number of arguments
- test nested udf functions, eg. func_a(func_b())

**Comment by shlee0605** [comment]
@YangMann Would you take over testing parts?

**Comment by shlee0605** [comment]
@ZheyuanBu @YangMann I think we all should start write test codes since now we can run SPI and PLPGSQL both. I think we shoul repeat(test -> fix) to make this support stable.

**Comment by ZheyuanBu** [comment]
Since we now have C, SPI and PLPGSQL, I think one person can take care of testing for one language.

**Comment by ZheyuanBu** [comment]
Useful link as an example of experiment.
[http://stackoverflow.com/questions/16992339/why-is-postgresql-array-access-so-much-faster-in-c-than-in-pl-pgsql](url)

**Comment by shlee0605** [comment]
closed
