### ISSUE TITLE
PL/pgSQL native loading

### ISSUE THREAD

**Issue by shlee0605** [shlee0605/peloton#6]
Currently, we can load plpgsql handler with any name except "plpgsql".
Let's fix this so that `$libdir/plpgsql.so` can be read and loaded as default.

**Comment by ZheyuanBu** [comment]
$libdir actually equals to `/usr/local/peloton/lib`.
So if you try to move the libplpgsql.so to that path and rename it to "plpgsql", you can `create procedural language plpgsql;` and it will create a language call "plpgsql".

**Comment by shlee0605** [comment]
As you said, I ran the following cmd at `/usr/local/peloton/lib`.
```
sudo ln -s /usr/local/lib/libplpgsql.so plpgsql
```
Then, `create procedural language plpgsql` works fine.
Let's also try to find the way to automatically load the language when we start the `psql`.

**Comment by ZheyuanBu** [comment]
I think it may be better if we load the language when we `initdb` instead of start `psql`, which starts a client.

**Comment by shlee0605** [comment]
That makes sense. I also checked that the loaded language is kept even if we restart the db or client. So, it requires only one time to load (just like the udfs).

**Comment by shlee0605** [comment]
@ZheyuanBu Can you check this part?
https://github.com/shlee0605/peloton/blob/master/tools/pg_initdb/initdb.cpp#L3385

**Comment by ZheyuanBu** [comment]
I also find this. Bu I put back those lines and it doesn't make any difference.

**Comment by shlee0605** [comment]
Let's try to run `CREATE EXTENSION plpgsql;` on peloton and if it does not work, lets change that to `create procedural language plpgsql;`

**Comment by shlee0605** [comment]
Also, it would be good if we can add some code to make a link to `/usr/local/peloton/lib/plpgsql` when we execute `make install`...

**Comment by ZheyuanBu** [comment]
'CREATE EXTENSION plpgsql;' has the same effect with 'create procedural language plpgsql;'. I've already tried this.

**Comment by shlee0605** [comment]
:sweat:

**Comment by ZheyuanBu** [comment]
I made plpgsql loaded automatically when the db is initialized.
pls pull the most recent commit and init a new db(`initdb ./data`)
you will see `loading PL/pgSQL server-side language ... ok` on your screen and `select * from pg_language` will have plpgsql in it.

**Comment by shlee0605** [comment]
@ZheyuanBu should we close this issue?
