### ISSUE TITLE
Fix warning when adding a function

### ISSUE THREAD

**Issue by shlee0605** [shlee0605/peloton#9]
Currently, we are getting the following warning when we add any udf function. 

```
07:00:18,618 [../../src/backend/bridge/ddl/ddl.cpp:100:ProcessUtility] WARN  - unrecognized node type: 723
```

Similarly, we are getting the following warning when we drop the function
```
07:15:58,988 [../../src/backend/bridge/ddl/ddl_table.cpp:154:ExecDropStmt] WARN  - Unsupported drop object 18
```

**Comment by shlee0605** [comment]
@ZheyuanBu Since udf function add/drop only needs to add information to `pg_proc`, peloton's ddl conversion & execution is not required (everything happens in postgres level). Do you think catching the type in the switch statement and immediately breaking make sense in this case?

**Comment by ZheyuanBu** [comment]
I think the "immediately breaking" way makes more sense since we don't need to execute the parsetree for udf.
